In [1]:
import pandas as pd
import numpy as np

In [2]:
#Question 1
from sklearn.datasets import load_digits
mnist=load_digits()

In [4]:
x=np.array(mnist.data)
y=mnist.target

In [6]:
#Question 2
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.25,random_state=42)

In [26]:
#Question 3
#(a)
from sklearn.svm import SVC
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report
lkernel=SVC(kernel="linear")
lkernel.fit(x_train,y_train)

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto_deprecated',
  kernel='linear', max_iter=-1, probability=False, random_state=None,
  shrinking=True, tol=0.001, verbose=False)

In [27]:
lpred=lkernel.predict(x_test)
print(confusion_matrix(y_test,lpred))
print("-------------------------------------------------------------------------------------------------")
print(classification_report(y_test,lpred))

[[43  0  0  0  0  0  0  0  0  0]
 [ 0 37  0  0  0  0  0  0  0  0]
 [ 0  0 38  0  0  0  0  0  0  0]
 [ 0  0  1 43  0  1  0  0  0  1]
 [ 0  1  0  0 54  0  0  0  0  0]
 [ 0  0  0  0  0 59  0  0  0  0]
 [ 0  0  0  0  0  0 45  0  0  0]
 [ 0  0  0  0  0  0  0 40  0  1]
 [ 0  0  0  0  0  1  0  0 37  0]
 [ 0  0  0  1  0  0  0  1  0 46]]
-------------------------------------------------------------------------------------------------
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        43
           1       0.97      1.00      0.99        37
           2       0.97      1.00      0.99        38
           3       0.98      0.93      0.96        46
           4       1.00      0.98      0.99        55
           5       0.97      1.00      0.98        59
           6       1.00      1.00      1.00        45
           7       0.98      0.98      0.98        41
           8       1.00      0.97      0.99        38
           9       0.96      0

In [28]:
#(b)
pkernel=SVC(kernel="poly")
pkernel.fit(x_train,y_train)
ppred=pkernel.predict(x_test)
print(confusion_matrix(y_test,ppred))
print("-------------------------------------------------------------------------------------------------")
print(classification_report(y_test,ppred))

[[43  0  0  0  0  0  0  0  0  0]
 [ 0 37  0  0  0  0  0  0  0  0]
 [ 0  0 38  0  0  0  0  0  0  0]
 [ 0  0  0 45  0  0  0  0  1  0]
 [ 0  0  0  0 55  0  0  0  0  0]
 [ 0  0  0  0  0 59  0  0  0  0]
 [ 0  0  0  0  0  0 45  0  0  0]
 [ 0  0  0  0  0  0  0 40  0  1]
 [ 0  0  0  0  0  1  0  0 37  0]
 [ 0  0  0  1  0  0  0  1  0 46]]
-------------------------------------------------------------------------------------------------
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        43
           1       1.00      1.00      1.00        37
           2       1.00      1.00      1.00        38
           3       0.98      0.98      0.98        46
           4       1.00      1.00      1.00        55
           5       0.98      1.00      0.99        59
           6       1.00      1.00      1.00        45
           7       0.98      0.98      0.98        41
           8       0.97      0.97      0.97        38
           9       0.98      0

C:\Users\Hp\Anaconda3\lib\site-packages\sklearn\svm\base.py:196: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)


In [24]:
#(c)
gkernel=SVC(kernel="rbf")
gkernel.fit(x_train,y_train)
gpred=gkernel.predict(x_test)
print(confusion_matrix(y_test,gpred))
print("-------------------------------------------------------------------------------------------------")
print(classification_report(y_test,gpred))

C:\Users\Hp\Anaconda3\lib\site-packages\sklearn\svm\base.py:196: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)


[[19  0  0  0  0  0  0  0 24  0]
 [ 0 27  0  0  0  0  0  0 10  0]
 [ 0  0 30  0  0  0  0  0  8  0]
 [ 0  0  0 34  0  0  0  0 12  0]
 [ 0  0  0  0 15  0  0  0 40  0]
 [ 0  0  0  0  0  1  0  0 58  0]
 [ 0  0  0  0  0  0 32  0 13  0]
 [ 0  0  0  0  0  0  0 27 14  0]
 [ 0  0  0  0  0  0  0  0 38  0]
 [ 0  0  0  0  0  0  0  0 36 12]]
-------------------------------------------------------------------------------------------------
              precision    recall  f1-score   support

           0       1.00      0.44      0.61        43
           1       1.00      0.73      0.84        37
           2       1.00      0.79      0.88        38
           3       1.00      0.74      0.85        46
           4       1.00      0.27      0.43        55
           5       1.00      0.02      0.03        59
           6       1.00      0.71      0.83        45
           7       1.00      0.66      0.79        41
           8       0.15      1.00      0.26        38
           9       1.00      0

In [25]:
#(d)
skernel=SVC(kernel="sigmoid")
skernel.fit(x_train,y_train)
spred=skernel.predict(x_test)
print(confusion_matrix(y_test,spred))
print("-------------------------------------------------------------------------------------------------")
print(classification_report(y_test,spred))

C:\Users\Hp\Anaconda3\lib\site-packages\sklearn\svm\base.py:196: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)


[[ 0 43  0  0  0  0  0  0  0  0]
 [ 0 37  0  0  0  0  0  0  0  0]
 [ 0 38  0  0  0  0  0  0  0  0]
 [ 0 46  0  0  0  0  0  0  0  0]
 [ 0 55  0  0  0  0  0  0  0  0]
 [ 0 59  0  0  0  0  0  0  0  0]
 [ 0 45  0  0  0  0  0  0  0  0]
 [ 0 41  0  0  0  0  0  0  0  0]
 [ 0 38  0  0  0  0  0  0  0  0]
 [ 0 48  0  0  0  0  0  0  0  0]]
-------------------------------------------------------------------------------------------------
              precision    recall  f1-score   support

           0       0.00      0.00      0.00        43
           1       0.08      1.00      0.15        37
           2       0.00      0.00      0.00        38
           3       0.00      0.00      0.00        46
           4       0.00      0.00      0.00        55
           5       0.00      0.00      0.00        59
           6       0.00      0.00      0.00        45
           7       0.00      0.00      0.00        41
           8       0.00      0.00      0.00        38
           9       0.00      0

C:\Users\Hp\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1143: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
